#!/usr/bin/env bash

_service=1

if [[ -n "$1" ]]; then
  _service="$1"
fi

_service_line=""
read -rt 0.1 _service_line

if [[ -z "${_service_line}" ]]; then
  _multiupload_secret="$(passveil show peertube/multiupload.json)"
  _service_line="$(echo "$_multiupload_secret" | jq -c '.[]' | sed "${_service}q;d")"
fi

echo "$_service_line" | jq -r ".address"
echo "$_service_line" | jq -r ".username"
echo "$_service_line" | jq -r ".password"
